apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: 970547376646.dkr.ecr.eu-north-1.amazonaws.com/eks-assignment:latest
        ports:
        - containerPort: 3000
        env:
        - name: SQLITE_DB_LOCATION
          value: "/app/data/todo.db"  # Point to the persisted directory
        volumeMounts:
        - mountPath: "/app/data"      # Mount PVC here
          name: todo-storage
      volumes:
      - name: todo-storage
        persistentVolumeClaim:
          claimName: todo-pvc