apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # Default EBS storage class
  resources:
    requests:
      storage: 1Gi